'use server';

// Server actions for the `quotes` table.
// Mirrors src/lib/invoices/actions.ts but for quotes (different status set,
// no `due_date` column, no .docx generation yet — quotes use the PDF
// generated by DocumentForm).
//
// IMPORTANT: 'use server' files can only export async functions. Status
// labels + styles live in ./constants.ts and are re-exported separately.

import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { QUOTE_STATUSES } from './constants';

const quoteStatusSchema = z.enum(QUOTE_STATUSES);

export async function setQuoteStatus(id: string, status: string) {
  const parsed = quoteStatusSchema.safeParse(status);
  if (!parsed.success) return { ok: false as const, error: 'invalid_status' };
  const supabase = await createClient();
  if (!supabase) return { ok: false as const, error: 'unauthorized' };
  const { error } = await supabase
    .from('quotes')
    .update({ status: parsed.data })
    .eq('id', id);
  if (error) return { ok: false as const, error: error.message };
  revalidatePath('/admin', 'layout');
  return { ok: true as const };
}

export async function deleteQuote(id: string) {
  const supabase = await createClient();
  if (!supabase) return { ok: false as const, error: 'unauthorized' };
  const { error } = await supabase.from('quotes').delete().eq('id', id);
  if (error) return { ok: false as const, error: error.message };
  revalidatePath('/admin', 'layout');
  return { ok: true as const };
}
