'use server';

// Server actions for the `quotes` table.
// Mirrors src/lib/invoices/actions.ts but for quotes (different status set,
// no `due_date` column, no .docx generation yet — quotes use the PDF
// generated by DocumentForm).
//
// IMPORTANT: 'use server' files can only export async functions. Status
// labels + styles live in ./constants.ts and are re-exported separately.

import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { QUOTE_STATUSES } from './constants';

// line_items: array of {description, quantity, unit_price, taxable}
const lineItemSchema = z.object({
  description: z.string().min(1, 'الوصف مطلوب').max(500),
  quantity: z.number().positive('الكمية يجب أن تكون أكبر من صفر'),
  unit_price: z.number().nonnegative('السعر لا يمكن أن يكون سالباً'),
  taxable: z.boolean().default(true),
});

// Note: `quotes.project_id` was added in migration 0007 (mirroring what
// 0003 did for `invoices`). The form sends an empty string when no
// project is selected; the action normalizes that to NULL on write.
const quoteSchema = z.object({
  client_id: z.string().uuid('معرّف العميل غير صالح'),
  project_id: z.string().uuid().optional().or(z.literal('')),
  issue_date: z.string().min(1, 'تاريخ الإصدار مطلوب'),
  valid_until: z.string().optional().default(''),
  currency: z.string().max(8).default('SAR'),
  vat_rate: z.string().default('15'),   // percent as string
  status: z.enum(QUOTE_STATUSES).default('draft'),
  notes: z.string().max(2000).optional().default(''),
  data: z.string().default('{}'),
  client_snapshot: z.string().default('{}'),
  line_items_json: z.string().default('[]'),
});

export type LineItem = z.infer<typeof lineItemSchema>;

function safeParseItems(json: string): LineItem[] {
  try {
    const arr = JSON.parse(json);
    if (!Array.isArray(arr)) return [];
    return arr
      .filter((x): x is LineItem =>
        typeof x === 'object' && x !== null && typeof x.description === 'string'
      )
      .map((x) => ({
        description: String(x.description),
        quantity: Number(x.quantity) || 0,
        unit_price: Number(x.unit_price) || 0,
        taxable: x.taxable !== false,
      }));
  } catch {
    return [];
  }
}

function computeTotals(items: LineItem[], vatRate: number) {
  const subtotal = items.reduce((s, it) => s + it.quantity * it.unit_price, 0);
  const taxableBase = items.filter((it) => it.taxable).reduce((s, it) => s + it.quantity * it.unit_price, 0);
  const vatAmount = Math.round(taxableBase * (vatRate / 100) * 100) / 100;
  const total = Math.round((subtotal + vatAmount) * 100) / 100;
  return { subtotal: Math.round(subtotal * 100) / 100, vatAmount, total };
}

export async function setQuoteStatus(id: string, status: string) {
  const parsed = z.enum(QUOTE_STATUSES).safeParse(status);
  if (!parsed.success) return { ok: false as const, error: 'invalid_status' };
  const supabase = await createClient();
  if (!supabase) return { ok: false as const, error: 'unauthorized' };
  const { error } = await supabase
    .from('quotes')
    .update({ status: parsed.data })
    .eq('id', id);
  if (error) return { ok: false as const, error: error.message };
  revalidatePath('/admin', 'layout');
  return { ok: true as const };
}

/**
 * Form-action wrapper for the status transitions on the quote detail page.
 *
 * Why a separate exported action: the page renders multiple transition
 * buttons (one per next-state) inside a `.map()`. An inline `action={async
 * () => { 'use server'; ... }}` inside a loop creates an unstable function
 * reference on every render, and Next.js 15/16 can't register a stable
 * action ID for it — the server-component render then throws, which the
 * route-level error boundary turns into the "حدث خطأ غير متوقع" page.
 *
 * Pulling the action out to this `use server` module gives every form a
 * stable function reference; the per-button parameter (the next status) is
 * passed via a hidden input. Same pattern is used for the delete form.
 *
 * Returns `void` because the form `action` prop's type signature is
 * `(formData) => void | Promise<void>`. Errors are swallowed here and
 * surfaced via the standard `revalidatePath('/admin', 'layout')` on
 * success / no-op on failure; the page is revalidated either way.
 */
export async function setQuoteStatusFormAction(formData: FormData): Promise<void> {
  const id = String(formData.get('id') ?? '');
  const status = String(formData.get('status') ?? '');
  if (!id) return;
  await setQuoteStatus(id, status);
}

/**
 * Form-action wrapper for the delete button on the quote detail page. Same
 * rationale as `setQuoteStatusFormAction` above — keeps the action reference
 * stable across renders.
 */
export async function deleteQuoteFormAction(formData: FormData): Promise<void> {
  const id = String(formData.get('id') ?? '');
  if (!id) return;
  await deleteQuote(id);
}

export async function deleteQuote(id: string) {
  const supabase = await createClient();
  if (!supabase) return { ok: false as const, error: 'unauthorized' };
  const { error } = await supabase.from('quotes').delete().eq('id', id);
  if (error) return { ok: false as const, error: error.message };
  revalidatePath('/admin', 'layout');
  return { ok: true as const };
}

/**
 * Update an existing quote.
 *
 *  - Recomputes subtotal/VAT/total from the submitted line items.
 *  - Rebuilds client_snapshot from the current client row (if any), so it
 *    stays in sync with the latest client data. Falls back to the snapshot
 *    in the form input when the client_id is empty.
 *  - Preserves data.valid_until in the JSONB blob (the .docx/PDF template
 *    engine reads it). The row's table (`quotes`) already encodes the
 *    kind, so the blob no longer needs to repeat it.
 *  - Never touches `number` or `created_by` — those are immutable after
 *    creation.
 */
export async function updateQuote(id: string, input: z.infer<typeof quoteSchema>) {
  const parsed = quoteSchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false as const, error: parsed.error.issues[0]?.message ?? 'invalid' };
  }
  const supabase = await createClient();
  if (!supabase) return { ok: false as const, error: 'unauthorized' };

  const items = safeParseItems(parsed.data.line_items_json);
  const vatRate = Number(parsed.data.vat_rate) || 0;
  const { subtotal, vatAmount, total } = computeTotals(items, vatRate);

  // Rebuild client_snapshot from the current client row. If the client was
  // removed or the form sends an empty client_id, fall back to whatever the
  // caller passed in (so we don't wipe the snapshot to {}).
  let snapshot: Record<string, unknown> = {};
  if (parsed.data.client_id) {
    const { data: client } = await supabase
      .from('clients')
      .select('id, name, email, phone, company, vat_number, address')
      .eq('id', parsed.data.client_id)
      .maybeSingle();
    const row = client as
      | {
          name: string;
          email: string | null;
          phone: string | null;
          company: string | null;
          vat_number: string | null;
          address: string | null;
        }
      | null;
    if (row) {
      snapshot = {
        name: row.name,
        email: row.email ?? undefined,
        phone: row.phone ?? undefined,
        company: row.company ?? undefined,
        vat_number: row.vat_number ?? undefined,
        address: row.address ?? undefined,
      };
    } else {
      snapshot = JSON.parse(parsed.data.client_snapshot || '{}');
    }
  } else {
    snapshot = JSON.parse(parsed.data.client_snapshot || '{}');
  }

  // Preserve the metadata fields the template engine relies on.
  const existingData = JSON.parse(parsed.data.data || '{}') as Record<string, unknown>;
  const dataBlob = {
    ...existingData,
    line_items: items,
    valid_until: parsed.data.valid_until || null,
    subtotal,
    vat_rate: vatRate,
    vat_amount: vatAmount,
    total,
  };

  const { data: updated, error } = await supabase
    .from('quotes')
    .update({
      client_id: parsed.data.client_id,
      project_id: parsed.data.project_id || null,
      client_snapshot: snapshot,
      data: dataBlob,
      subtotal,
      vat_rate: vatRate,
      vat_amount: vatAmount,
      total,
      currency: parsed.data.currency,
      status: parsed.data.status,
      issue_date: parsed.data.issue_date,
      valid_until: parsed.data.valid_until || null,
      notes: parsed.data.notes || null,
    })
    .eq('id', id)
    .select('id')
    .single();
  if (error) return { ok: false as const, error: error.message };
  // No row matched the id — most likely the quote was deleted between page
  // load and submit. Surface it as an error so the form doesn't silently
  // claim success.
  if (!updated) {
    return { ok: false as const, error: 'quote_not_found' };
  }

  revalidatePath('/admin', 'layout');
  return { ok: true as const };
}
