// src/lib/pdf/types.ts
// Shared data shape for all PDF documents generated by the admin.

export type DocumentKind = 'invoice' | 'quote';

export type LineItem = {
  description: string;
  quantity: number;
  unit_price: number;  // SAR per unit (line total = quantity × unit_price)
  taxable?: boolean;  // default true
};

export type DocumentData = {
  kind: DocumentKind;

  // Brand
  brand: {
    nameAr: string;
    nameEn: string;
    taglineAr?: string;
    taglineEn?: string;
    cr: string;
    vat: string;
    address: string;
    email: string;
    phone: string;
    website: string;
  };

  // Document header
  number: string;          // INV-2026-001 or QT-2026-001
  issue_date: string;      // yyyy-mm-dd
  valid_until?: string;    // quotes only (yyyy-mm-dd)

  // Client snapshot
  client: {
    name: string;
    company: string | null;
    vat_number: string | null;
    address: string | null;
    email: string | null;
    phone: string | null;
  };

  // Line items
  line_items: LineItem[];

  // Totals (computed in the action; passed in for display)
  subtotal: number;
  vat_rate: number;        // percent (15 = 15%)
  vat_amount: number;
  total: number;

  // Optional
  notes: string | null;
  currency: string;        // 'SAR'
};
