import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHmac, randomBytes } from 'node:crypto';
import ts from 'typescript';
import { PGlite } from '@electric-sql/pglite';

const source = await readFile(new URL('../src/lib/meta/security.ts', import.meta.url), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext } }).outputText;
const security = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const raw = JSON.stringify({ text: 'مرحبا' });
const signature = 'sha256=' + createHmac('sha256', 'secret').update(raw).digest('hex');
assert.equal(security.verifySignature(raw, signature, 'secret'), true);
assert.equal(security.verifySignature(raw + ' ', signature, 'secret'), false);
assert.equal(security.verifySignature(raw, 'sha256=invalid', 'secret'), false);
assert.equal(security.verifySignature(raw, null, 'secret'), false);
process.env.META_TOKEN_ENCRYPTION_KEY = randomBytes(32).toString('base64');
const encrypted = security.encryptToken('test-token');
assert.equal(security.decryptToken(encrypted), 'test-token');
const pieces = encrypted.split('.'); pieces[2] = Buffer.from('tampered').toString('base64');
assert.throws(() => security.decryptToken(pieces.join('.')));
assert.equal(security.normalizePhone('+966 50-000-0000'), '966500000000');
assert.throws(() => security.normalizePhone('0500000000'));

// Exercise the actual HTTP handlers with a controlled persistence boundary.
let persisted = 0, failPersistence = false;
globalThis.metaTestDb = { rpc: async () => { persisted++; return { error: failPersistence ? { message:'unavailable' } : null }; } };
const routeSource = (await readFile(new URL('../src/app/api/meta/whatsapp/webhook/route.ts',import.meta.url),'utf8'))
 .replace("import { createAdminClient } from '@/lib/supabase/admin';", 'const createAdminClient = () => globalThis.metaTestDb;')
 .replace("'@/lib/meta/security'", JSON.stringify(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`));
const route = await import(`data:text/javascript;base64,${Buffer.from(ts.transpileModule(routeSource,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')}`);
process.env.META_APP_SECRET='handler-secret'; process.env.META_WEBHOOK_VERIFY_TOKEN='verify-secret';
assert.equal((await route.GET(new Request('https://example.test/?hub.mode=subscribe&hub.verify_token=wrong&hub.challenge=challenge'))).status,403);
assert.equal(await (await route.GET(new Request('https://example.test/?hub.mode=subscribe&hub.verify_token=verify-secret&hub.challenge=challenge'))).text(),'challenge');
const eventBody=JSON.stringify({object:'whatsapp_business_account',entry:[]});
const sign='sha256='+createHmac('sha256','handler-secret').update(eventBody).digest('hex');
const httpRequest=signature=>new Request('https://example.test/',{method:'POST',body:eventBody,headers:{'x-hub-signature-256':signature}});
assert.equal((await route.POST(httpRequest('invalid'))).status,403); assert.equal(persisted,0);
failPersistence=true; assert.equal((await route.POST(httpRequest(sign))).status,503);
failPersistence=false; assert.equal((await route.POST(httpRequest(sign))).status,200);
assert.equal((await route.POST(new Request('https://example.test/',{method:'POST',body:'x'.repeat(1_048_577)}))).status,413);
delete globalThis.metaTestDb;

const db = new PGlite();
const actor = '00000000-0000-4000-8000-000000000001';
const outsider = '00000000-0000-4000-8000-000000000002';
const tenant = '10000000-0000-4000-8000-000000000001';
const other = '10000000-0000-4000-8000-000000000002';
const request = '20000000-0000-4000-8000-000000000001';
const query = async (sql, params=[]) => (await db.query(sql,params)).rows[0]?.result;
try {
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
 create schema auth; create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth to authenticated,service_role;
 create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');
 create table public.users(id uuid primary key,email text,full_name text,role text default 'editor' constraint users_role_check check(role in ('owner','editor')));
 create function public.tg_handle_new_user() returns trigger language plpgsql as $$ begin return new; end $$;
 insert into public.users values('${actor}','owner@test.invalid','Owner','owner'),('${outsider}','other@test.invalid','Other','owner');`);
 for (const name of ['20260916084850_merchant_subscriptions.sql','20260916123743_meta_cloud_api.sql','20260917163851_ycloud_provider.sql']) await db.exec(await readFile(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8'));
 await db.exec(`insert into public.tenants(id,name,is_test) values('${tenant}','First',true),('${other}','Second',true);
 insert into public.tenant_members values('${tenant}','${actor}','owner'),('${other}','${outsider}','owner');
 insert into public.subscriptions values('${tenant}','starter_v1','active',now()-interval '1 day',now()+interval '29 days'),('${other}','starter_v1','active',now()-interval '1 day',now()+interval '29 days');
 grant select on public.users to service_role; set role service_role;`);
 const bindArgs=[tenant,actor,'+966500000000','123','456',encrypted,'test'];
 const bindSql='select public.soulvd_meta_bind($1,$2,$3,$4,$5,$6,$7) as result';
 const number = await query(bindSql,bindArgs);
 assert.equal(await query(bindSql,bindArgs),number);
 await assert.rejects(query(bindSql,[other,outsider,'+966500000000','123','456',encrypted,'test']),/NUMBER_ALREADY_BOUND/);
 const event=(id,time=Date.now()/1000) => ({object:'whatsapp_business_account',entry:[{id:'123',changes:[{field:'messages',value:{metadata:{phone_number_id:'456'},messages:[{id,from:'966511111111',timestamp:String(Math.floor(time)),type:'text',text:{body:'مرحبا'}}]}}]}]});
 assert.equal(await query('select public.soulvd_meta_ingest($1,$2) as result',['event1',event('incoming1')]),true);
 assert.equal(await query('select public.soulvd_meta_ingest($1,$2) as result',['event1',event('incoming1')]),false);
 await query('select public.soulvd_meta_ingest($1,$2) as result',['event2',event('incoming1')]);
 assert.equal(await query('select count(*)::int as result from public.whatsapp_messages'),1);
 const enqueue='select public.soulvd_meta_enqueue($1,$2,$3,$4,$5,$6,$7,$8) as result';
 const args=[tenant,actor,request,'message','966511111111','Reply',null,false];
 const queued=await query(enqueue,args); assert.equal(queued.allowed,true);
 assert.equal((await query(enqueue,args)).id,queued.id);
 await assert.rejects(query(enqueue,[...args.slice(0,5),'Changed',null,false]),/REQUEST_CONFLICT/);
 await assert.rejects(query(enqueue,[other,actor,request,'message','966511111111','Cross tenant',null,false]),/FORBIDDEN/);
 const closed=await query(enqueue,[tenant,actor,'20000000-0000-4000-8000-000000000002','message','966522222222','No inbound',null,false]);
 assert.equal(closed.code,'WINDOW_CLOSED');
 const claim=await query('select public.soulvd_meta_claim($1) as result',[queued.id]); assert.equal(claim.id,queued.id);
 assert.equal(await query('select public.soulvd_meta_claim($1) as result',[queued.id]),null);
 await query('select public.soulvd_meta_finish($1,$2,$3,$4) as result',[queued.id,'accepted','outgoing1',null]);
 const statusEvent=status=>({object:'whatsapp_business_account',entry:[{id:'123',changes:[{field:'messages',value:{metadata:{phone_number_id:'456'},statuses:[{id:'outgoing1',status}]}}]}]});
 await query('select public.soulvd_meta_ingest($1,$2) as result',['read',statusEvent('read')]);
 await query('select public.soulvd_meta_ingest($1,$2) as result',['sent',statusEvent('sent')]);
 assert.equal(await query("select status as result from public.whatsapp_messages where meta_message_id='outgoing1'"),'read');
 const template=await query(enqueue,[tenant,actor,'20000000-0000-4000-8000-000000000003','template','',JSON.stringify({name:'review_test',language:'ar',category:'UTILITY',components:[{type:'BODY',text:'Test'}]}),null,false]);
 assert.equal(template.allowed,true);
 assert.equal(await query("select status as result from public.whatsapp_templates where name='review_test'"),'pending');
 assert.equal(await query('select public.soulvd_meta_claim($1) as result',[template.id]),null,'per-number claim spacing');
 await db.exec(`update soulvd_private.meta_jobs set claimed_at=now()-interval '2 seconds' where id='${queued.id}';`);
 const claimedTemplate=await query('select public.soulvd_meta_claim($1) as result',[template.id]); assert.equal(claimedTemplate.id,template.id);
 await db.exec(`update soulvd_private.meta_jobs set claimed_at=now()-interval '6 minutes' where id='${template.id}';`);
 await query('select public.soulvd_meta_claim(null) as result');
 assert.equal(await query('select status as result from soulvd_private.meta_jobs where id=$1',[template.id]),'unknown');
 await db.exec(`update public.usage_counters set conversations_used=2000;`);
 await query('select public.soulvd_meta_ingest($1,$2) as result',['atcap',{object:'whatsapp_business_account',entry:[{id:'123',changes:[{field:'messages',value:{metadata:{phone_number_id:'456'},messages:[{id:'atcap',from:'966533333333',timestamp:String(Math.floor(Date.now()/1000)),type:'text',text:{body:'Keep me'}}]}}]}]}]);
 assert.equal(await query("select count(*)::int as result from public.whatsapp_messages where meta_message_id='atcap'"),1);
 assert.equal((await query(enqueue,[tenant,actor,'20000000-0000-4000-8000-000000000004','message','966533333333','New customer blocked',null,false])).code,'LIMIT_EXCEEDED');
 await db.exec(`reset role; set role authenticated; set request.jwt.claim.sub='${outsider}';`);
 assert.equal(await query('select count(*)::int as result from public.whatsapp_messages'),0);
 await assert.rejects(query('select public.soulvd_meta_claim(null) as result'),/permission denied/);
 await assert.rejects(query('select * from soulvd_private.meta_connections'),/permission denied/);
 await db.exec('reset role; set role service_role;');
 const ynumber = await query('select public.soulvd_ycloud_bind($1,$2,$3,$4,$5,$6,$7) as result',[other,outsider,'+966500000001','789','987',encrypted,'test']);
 await assert.rejects(query(bindSql,[other,outsider,'+966500000001','789','987',encrypted,'test']),/NUMBER_MISMATCH/);
 const yin={id:'evt-in',type:'whatsapp.inbound_message.received',whatsappInboundMessage:{id:'incoming-y',wabaId:'789',from:'+966511111111',to:'+966500000001',sendTime:new Date().toISOString(),type:'text',text:{body:'Y test'},customerProfile:{name:'Tester'}}};
 const yingest='select public.soulvd_ycloud_ingest($1,$2) as result';
 assert.equal(await query(yingest,[yin.id,yin]),true);
 assert.equal(await query(yingest,[yin.id,yin]),false);
 assert.equal(await query('select count(*)::int as result from public.whatsapp_messages where number_id=$1',[ynumber]),1);
 assert.equal(await query('select conversations_used as result from public.usage_counters where tenant_id=$1',[other]),1);
 const yqueued = await query(enqueue,[other,outsider,'20000000-0000-4000-8000-000000000007','message','966511111111','Y reply',null,false]);
 const yjob=await query('select public.soulvd_meta_claim($1) as result',[yqueued.id]);
 assert.equal(yjob.provider,'ycloud'); assert.equal(yjob.phone,'+966500000001');
 const receipt={id:'evt-receipt',type:'whatsapp.message.updated',whatsappMessage:{id:'out-y',wabaId:'789',from:'+966500000001',to:'+966511111111',status:'read'}};
 await query(yingest,[receipt.id,receipt]);
 await query('select public.soulvd_meta_finish($1,$2,$3,$4) as result',[yqueued.id,'accepted','ycloud:out-y',null]);
 assert.equal(await query("select status as result from public.whatsapp_messages where meta_message_id='ycloud:out-y'"),'read');
 const wrong={...yin,id:'evt-other',whatsappInboundMessage:{...yin.whatsappInboundMessage,wabaId:'123',id:'wrong'}};
 await query(yingest,[wrong.id,wrong]);
 assert.equal(await query('select count(*)::int as result from public.whatsapp_messages where number_id=$1',[ynumber]),2);
 await query('select public.soulvd_meta_sync_templates($1,$2,$3) as result',[other,outsider,[{name:'y_test',language:'ar',body:'Template',category:'UTILITY',status:'APPROVED'}]]);
 const paused={id:'evt-paused',type:'whatsapp.template.reviewed',whatsappTemplate:{wabaId:'789',name:'y_test',language:'ar',status:'PAUSED'}};
 await query(yingest,[paused.id,paused]);
 assert.equal(await query("select status as result from public.whatsapp_templates where tenant_id=$1 and name='y_test'",[other]),'rejected');
 assert.equal(await query("select provider_status as result from public.whatsapp_templates where tenant_id=$1 and name='y_test'",[other]),'PAUSED');
 await db.exec(`reset role; set role authenticated; set request.jwt.claim.sub='${actor}';`);
 assert.equal(await query('select count(*)::int as result from public.whatsapp_messages where tenant_id=$1',[other]),0);
 await assert.rejects(query(yingest,[yin.id,yin]),/permission denied/);
 console.log('PASS: Meta + YCloud provider isolation, RLS, deduplication, quota/window gates, single dispatch, receipt ordering and template reservations.');
} finally { await db.close(); }
